### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by Daoro** [Mayeu/mayeu.me#1]
< script src='//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js' ></ script >
At least, selfhost that shit :)

(but seeing it is only used by bootstrap, do you really need javascript on your page ?)

**Comment by Mayeu** [comment]
Working on the next releases that with drop all JS need :)

**Comment by Mayeu** [comment]
Fixed with the last release.
